name: Unit Tests
on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Install dependencies
        run: |
          pip install pytest
          
      - name: Run unit tests
        run: pytest
          
